FROM mcr.microsoft.com/devcontainers/python:3-trixie

# Install Node.js & and dependencies for claude sandbox mode
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && apt-get install -y --no-install-recommends \
  nodejs \
  bubblewrap \
  socat \
  && rm -rf /var/lib/apt/lists/*

# Dependencies for claude sandbox mode
RUN npm install -g @anthropic-ai/sandbox-runtime

RUN mkdir -p /home/vscode/.claude && chown vscode:vscode /home/vscode/.claude

USER vscode

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.11.3 /uv /uvx /bin/

# Install claude code
RUN curl -fsSL https://claude.ai/install.sh | bash

