FROM mcr.microsoft.com/devcontainers/python:3-trixie


RUN mkdir -p /home/vscode/.claude && chown vscode:vscode /home/vscode/.claude

USER vscode

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.11.3 /uv /uvx /bin/

# Install claude code
RUN curl -fsSL https://claude.ai/install.sh | bash

