FROM mcr.microsoft.com/devcontainers/python:3-trixie

# Install Homebrew
USER vscode
RUN NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# Add env vars and zsh completions to ~/.zshrc
RUN cat <<EOF >> ~/.zshrc
# Homebrew env vars
eval "\$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# Homebrew zsh completions
if type brew &>/dev/null; then
  FPATH="\$(brew --prefix)/share/zsh/site-functions:\${FPATH}"
  autoload -Uz compinit
  compinit
fi
EOF

ENV PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}"

RUN brew install zsh-completions dive

RUN sudo apt-get update && sudo apt-get install --no-install-recommends --yes vim rsync

# Set zsh as default shell
RUN sudo chsh -s /bin/zsh vscode

# Install UV
COPY --from=ghcr.io/astral-sh/uv:0.9.12 /uv /uvx /bin/

